### ISSUE TITLE
Add JSDoc for RESTMessageV2.d.ts

### ISSUE THREAD

**Issue by johncaruso** [u-now/types-x#33]

**Comment by emyrold** [comment]
@johncaruso this is kicking my ass...  I've been googling the correct syntax for JSDoc where there is a "declare namespace" in the d.ts . in this RESTMessage there are two things I do not know how to address,  declare namespace sn_ws {} and at the very bottom type RestHTTPMethods = . I'm cross checking with developer api and do not see the type referenced there and it is highlighted blue lik the declare and constructor.

**Comment by emyrold** [comment]
```javascript
declare namespace sn_ws {
  declare class RESTMessageV2 {
    constructor();
    constructor(name: string, methodName: RestHTTPMethods);
    execute(): RESTResponseV2;
    // ...
    setStringParameterNoEscape(name: string, value: string): void;
  }

  type RestHTTPMethods =
    | 'get'
    | 'post'
    | 'delete'
    | 'patch'
    | 'put'
    | 'head'
    | 'delete'
    | 'options';
}

```

**Comment by johncaruso** [comment]
Understand that there is overlap between things in JSDoc and d.ts
(TypeScript definitions). Not everything needs a JSDoc, if is has a
corresponding d.ts.

For this case, while there is a tag for namespaces, there is no point in
including it here, as the d.ts itself documents the namespace and a member
of that namespace: RESTMessageV2

Now if you were just using plain JavaScript without d.ts files, then you
might want to use the tags @namespace and @memberof as documented here:
http://usejsdoc.org/tags-namespace.html

Regarding the type RestHTTPMethods, this again is something where a
corresponding JSDoc would just duplicate the d.ts. But for your reference,
if not using d.ts, it would be:

@typedef {'get' | 'post' | '...'} RestHTTPMethods

(I think.)
